Feature/CC-0059 Order Generation
courtcanva/cc-server pull request #93
Opened 2022-10-19 02:39 UTC by wwwseven

**Added files**: module, controller, service, schema, dto, testing for controller and service.

**Main functions**: findAll, findOne, create, update, delete.

**Order schema**: https://drive.google.com/file/d/1K_8si1ma0ugCQ5teiYrVlDBEtYPWqNO7/view

**Postman**: 
[order.postman_collection.json.zip](https://github.com/courtcanva/cc-server/files/9816338/order.postman_collection.json.zip)

2022-10-19 12:34 UTC, RedRe4per reviewed
Good work, with a few problems.

-----------------old-------------------------------
Since create order is a procedure with 2 steps, create unpaid order without user info, and update order with payment state & user info. My sugguestion is, you can try to add an extra "createOrder2.dto" or "finishOrder.dto" or something else. It includes data which are obtained by Stripe webhook.

-----------------new------------------------------
As discussed yesterday, the best solution is to change the schema. Please delete the payment related parts in the schema, they will be moved to a payment table. After that, please reserve the payment Ref field for future payment table.
In this solution, the dto will be no different from the normal dto.

2022-10-19 12:34 UTC, RedRe4per commented on src/orders/dto/updateOrder.dto.ts
> +  isPaid: boolean;
@Exclude or delete, determined by if createOrderDto includes this field. Because this field is updated by stripe info.

2022-10-19 12:34 UTC, RedRe4per commented on src/orders/dto/updateOrder.dto.ts
> +  stripeSessionId: string;
@Exclude or delete, determined by if createOrderDto includes this field. Because this field is updated by stripe info.

2022-10-19 12:34 UTC, RedRe4per commented on src/orders/dto/updateOrder.dto.ts
> +  currency: string;
@Exclude or delete, determined by if createOrderDto includes this field. Because this field is updated by stripe info.@exclude

2022-10-19 12:34 UTC, RedRe4per commented on src/orders/dto/updateOrder.dto.ts
> +  @IsOptional()
@Exclude or delete, determined by if createOrderDto includes this field. Because this field is updated by stripe info.@exclude

2022-10-28 02:15 UTC, RedRe4per requested changes

2022-10-28 05:45 UTC, RedRe4per approved these changes
LGTM

2022-10-28 05:48 UTC, GLC-coder approved these changes
lgtm

2022-10-28 05:50 UTC, merged